Repository CAN-Group/can, pull requests merged in 2021-01, with the labels that each got.

#23 Feature/remaining endpoints
  flask-app/app.py
Labels: backend, enhancement

#2 Add python scraper for COVID-19 figures
  .gitignore
  scraper/.flake8
  scraper/Pipfile
  scraper/Pipfile.lock
  scraper/database.py
  scraper/main.py
  scraper/models.py
  scraper/pyproject.toml
  scraper/scheduler.py
  scraper/scrape.py
  scraper/settings.py
  scraper/static_data/counties.csv
  scraper/static_data_api.py
Labels: enhancement, scraping

#26 Feature/docker
  compose-dev.sh
  compose-prod.sh
  docker-compose.dev.yaml
  docker-compose.yaml
  dockerbuild.sh
  flask-app/.dockerignore
  flask-app/Dockerfile
  flask-app/Pipfile
  flask-app/Pipfile.lock
  flask-app/app.py
  flask-app/build.sh
  flask-app/run.sh
  flask-app/wsgi.py
  scraper/.dockerignore
  scraper/Dockerfile
  scraper/build.sh
Labels: backend, brouter, enhancement, scraping

#29 Add new brouter proxy endpoint
  flask-app/app.py
  flask-app/route_args.py
Labels: backend, enhancement

#30 implement frontend
  can-frontend/.gitignore
  can-frontend/README.md
  can-frontend/package-lock.json
  can-frontend/package.json
  can-frontend/public/data/counties.csv
  can-frontend/public/data/test.csv
  can-frontend/public/images/icons/MarkerA.png
  can-frontend/public/images/icons/MarkerB.png
  can-frontend/public/images/logo.png
  can-frontend/public/index.html
  can-frontend/public/robots.txt
  can-frontend/src/App.jsx
  can-frontend/src/assets/css/global-style.css
  can-frontend/src/assets/css/reset-style.css
  can-frontend/src/assets/metadata/cities.json
  can-frontend/src/assets/metadata/counties.json
  can-frontend/src/assets/metadata/counties_old.json
  can-frontend/src/components/Footer.jsx
  can-frontend/src/components/MainContent.jsx
  can-frontend/src/components/Navbar.jsx
  can-frontend/src/components/content/ContentWrapper.jsx
  can-frontend/src/components/content/InfoContent.jsx
  can-frontend/src/components/content/map/InfoBoxMap.jsx
  can-frontend/src/components/content/map/InputMap.jsx
  can-frontend/src/components/content/map/LeafletMap.jsx
  can-frontend/src/components/content/map/MapComponent.jsx
  can-frontend/src/components/content/map/MapPanel.jsx
  can-frontend/src/components/content/map/example.gpx
  can-frontend/src/components/helpers/AutoTextBox.jsx
  can-frontend/src/components/helpers/DraggableMarker.jsx
  can-frontend/src/components/helpers/SubmitButton.jsx
  can-frontend/src/components/helpers/SwitchButton.jsx
  can-frontend/src/components/helpers/js/apiCalls.js
  can-frontend/src/components/helpers/js/connection.js
  can-frontend/src/components/navigation/Logo.jsx
  can-frontend/src/components/navigation/MenuBar.jsx
  can-frontend/src/components/navigation/MenuItem.jsx
  can-frontend/src/index.js
  flask-app/static/cities.json
Labels: enhancement, frontend

#37 Update scraper to facilitate data source url & format changes
  scraper/main.py
  scraper/scrape.py
  scraper/settings.py
Labels: enhancement, scraping

#34 [Flask] Fix and update route v2 endpoint
  flask-app/.dockerignore
  flask-app/app.py
  flask-app/public/route_help.html
  flask-app/public/sitemap.html
  flask-app/route_args.py
  flask-app/router_proxy.py
  flask-app/static/routing_profiles.json
  flask-app/wsgi.py
Labels: backend, enhancement

#38 Restrict brouter route search to Poland
  flask-app/router_proxy.py
  flask-app/static/poland.outline
Labels: backend, brouter, enhancement

#45 Refactor/router proxy
  flask-app/Pipfile
  flask-app/Pipfile.lock
  flask-app/logs/.gitkeep
  flask-app/router_proxy.py
  flask-app/shapes.py
  flask-app/static/counties.geojson
  flask-app/static/poland.geojson
  flask-app/static/poland.outline
Labels: backend, brouter, enhancement

#47 [Flask] Fix exception in route proxy
  flask-app/router_proxy.py
Labels: backend, bugfix

#48 Change routing_profiles.json and default profile
  flask-app/router_proxy.py
  flask-app/static/routing_profiles.json
Labels: backend, brouter

#51 Refactor/docker
  flask-app/.dockerignore
  flask-app/Dockerfile
  flask-app/Pipfile
  flask-app/Pipfile.lock
  flask-app/build.sh
  flask-app/run.sh
  scraper/.dockerignore
  scraper/Dockerfile
Labels: backend, scraping

#49 [Frontend] Add Dockerfile
  can-frontend/.dockerignore
  can-frontend/Dockerfile
Labels: enhancement, frontend

#54 Translate route profiles friendly names to English
  flask-app/static/routing_profiles.json
Labels: backend, brouter

#56 Update flask after routing_profiles.json change
  flask-app/router_proxy.py
Labels: backend, bugfix

#57 fix navbar
  can-frontend/src/components/Navbar.jsx
Labels: bugfix, frontend
